---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: sonarr-secrets
    namespace: arr-stack
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: sonarr-secrets
  data:
    - secretKey: apikey
      remoteRef:
        key: "1e5e68ab-b585-48da-89fe-b46500ec2a23"