---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-root
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nolock
    - soft
    - rw
  nfs:
    server: ${NAS_DOMAIN}
    path: /volume1/media/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-root
  namespace: arr-stack
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  volumeName: media-root

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-media
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nolock
    - soft
    - rw
  nfs:
    server: ${NAS_DOMAIN}
    path: /volume1/media/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-media
  namespace: arr-stack
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  volumeName: media-media

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-torrents
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nolock
    - soft
    - rw
  nfs:
    server: ${NAS_DOMAIN}
    path: /volume1/media/torrents
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-torrents
  namespace: arr-stack
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  volumeName: media-torrents