---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: overseerr-certificate
  namespace: overseerr
spec:
  secretName: overseerr-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: seerr.${CLUSTER_DOMAIN}
  dnsNames:
    - seerr.${CLUSTER_DOMAIN}