apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./00-namespace.yml
  - ./01-pvc.yml
  - ./02-deployment.yml
  - ./03-service.yml
  - ./04-certificate.yaml
  - ./05-ingress.yml
