---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: arr-stack
spec:
  storageClassName: longhorn-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi