apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: tailscale-oauth
    namespace: tailscale
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: operator-oauth
  data:
    - secretKey: client_id
      remoteRef:
        key: "f8980ebb-d04c-4494-848a-b4b000c4bf9f"
    - secretKey: client_secret
      remoteRef:
        key: "04a92d6d-45a0-4acc-94ad-b4b000c4df2d"