apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-pv
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nas-01.aethernode.it
    path: /volume1/media/media
  mountOptions:
    - nolock
    - soft
    - rw

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 3Ti
  volumeName: plex-media-pv