---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  chartRef:
    kind: OCIRepository
    name: plex
  interval: 1h
  values:
    controllers:
      plex:
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/plex
              tag: 1.43.0
              pullPolicy: IfNotPresent
            
            env:
              TZ: Europe/Rome
              PUID: "1000"
              PGID: "1000"
              VERSION: docker
              PLEX_CLAIM: "claim-sK4z6wj3XNh3xxkLRNyy"
              PLEX_ADVERTISE_URL: https://plex.${CLUSTER_DOMAIN}:443,http://plex.plex.svc.cluster.local:32400
            
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: &port 32400
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                cpu: 4
                memory: 8Gi
    
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: plex
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: plex
        type: LoadBalancer
        ports:
          http:
            port: 32400
            protocol: TCP
    
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: nas-01.aethernode.it
        path: /volume1/media
        globalMounts:
          - path: /media
            readOnly: true
      tmp:
        type: emptyDir