apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: external-dns-unifi-secret
    namespace: external-dns
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: external-dns-unifi-secret
  data:
    - secretKey: api-key
      remoteRef:
        key: "3a9792b1-4aa9-493a-9965-b41e014ff2a0"