apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
  namespace: seerr
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: seerr
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    config:
      persistence:
        storageClass: longhorn
    ingress:
      enabled: true
      ingressClassName: cilium
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/hostname: seerr.${CLUSTER_DOMAIN}
      hosts:
        - host: seerr.${CLUSTER_DOMAIN}
      tls:
        - hosts:
            - seerr.${CLUSTER_DOMAIN}
          secretName: seerr-tls