apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: plex-claim
    namespace: plex
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: plex-claim
  data:
    - secretKey: PLEX_CLAIM
      remoteRef:
        key: "f33af2d2-4fc2-47be-87a1-b41a0150ae75"