---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: sso-client
    namespace: n8n
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: sso-client
  data:
    - secretKey: client_id
      remoteRef:
        key: "e36ab1bc-e70e-43eb-a902-b46500bfe6f4"
    - secretKey: client_secret
      remoteRef:
        key: "703a5f26-0fc2-4160-8de4-b46500c0019f"