---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: arr-stack
  labels:
    app: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
        - name: bazarr
          image: ghcr.io/hotio/bazarr:release-v1.5.5
          env:
            - name: TZ
              value: "Europe/Rome"
            - name: UMASK
              value: "002"
          ports:
            - containerPort: 6767
              name: http
          volumeMounts:
            - name: bazarr-config
              mountPath: /config
            - name: media-media
              mountPath: /data/media
          resources:
            requests:
              memory: "128Mi"
              cpu: "25m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: pvc-config-bazarr
        - name: media-media
          persistentVolumeClaim:
            claimName: pvc-media-media

---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: arr-stack
spec:
  selector:
    app: bazarr
  ports:
    - name: http
      port: 6767
      targetPort: 6767
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr
  namespace: arr-stack
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: bazarr.${CLUSTER_DOMAIN}
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - bazarr.${CLUSTER_DOMAIN}
      secretName: bazarr-tls
  rules:
    - host: bazarr.${CLUSTER_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bazarr
                port:
                  number: 6767