---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
  namespace: arr-stack
  labels:
    app: deluge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deluge
    spec:
      containers:
        - name: deluge
          image: lscr.io/linuxserver/deluge:2.2.0-libtorrentv1
          env:
            - name: TZ
              value: Europe/Rome
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: DELUGE_LOGLEVEL
              value: "info"
          ports:
            - name: http
              protocol: TCP
              containerPort: 8112
          volumeMounts:
            - name: deluge-config
              mountPath: /config
            - name: media-torrents
              mountPath: /data/torrents
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "500m"
      volumes:
        - name: deluge-config
          persistentVolumeClaim:
            claimName: pvc-config-deluge
        - name: media-torrents
          persistentVolumeClaim:
            claimName: pvc-media-torrents

---
apiVersion: v1
kind: Service
metadata:
  name: deluge
  namespace: arr-stack
spec:
  selector:
    app: deluge
  ports:
    - name: http
      port: 8112
      targetPort: 8112
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deluge
  namespace: arr-stack
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: deluge.${CLUSTER_DOMAIN}
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - deluge.${CLUSTER_DOMAIN}
      secretName: deluge-tls
  rules:
    - host: deluge.${CLUSTER_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deluge
                port:
                  number: 8112