apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: gluetun-secret
    namespace: arr-stack
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: gluetun-secret
  data:
    - secretKey: OPENVPN_USER
      remoteRef:
        key: "2b8a5442-24b1-40c9-b72b-b41e0135c38d"
    - secretKey: OPENVPN_PASSWORD
      remoteRef:
        key: "9232bfd5-f58e-4e76-94ab-b41e0135d6c1"
    - secretKey: WIREGUARD_SECRET
      remoteRef:
        key: "96c2c589-a859-48e9-ab22-b41e0136178c"