apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ./gluetun-configmap.yaml
- ./pv-pvc.yaml
- ./qbittorrent.yaml
- ./prowlarr.yaml
- ./radarr.yaml
- ./sonarr.yaml
- ./bazarr.yaml
- ./flaresolverr.yaml
- ./external-secrets.yaml