---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: arr-stack
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: ghcr.io/hotio/sonarr:release-4.0.16.2944
          env:
            - name: TZ
              value: "Europe/Rome"
          ports:
            - containerPort: 8989
              name: http
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: media-root
              mountPath: /data
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "300m"
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: pvc-config-sonarr
        - name: media-root
          persistentVolumeClaim:
            claimName: pvc-media-root
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: arr-stack
spec:
  selector:
    app: sonarr
  ports:
    - name: http
      port: 8989
      targetPort: 8989
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  namespace: arr-stack
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: sonarr.${CLUSTER_DOMAIN}
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - sonarr.${CLUSTER_DOMAIN}
      secretName: sonarr-tls
  rules:
    - host: sonarr.${CLUSTER_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989
