apiVersion: v1
data:
    secret_key: ENC[AES256_GCM,data:Y9ZUCLmJ4JEYTHe8NV71bao76aULP2IAvV76lhJCuk5ED6jwNmTawK4u1+MvqEAcbUJKcNpxftOKS+2mY65LGQTOoKDWM6PXQj5bXNjbDio03vM7CGI8AVm12oqa4siRyxX7LGAq1J4c4Jzp,iv:S5tPPArZIC0rkfIEz8clXn077BpV3j0fNTVJ5aH+v4I=,tag:sfygmLEw5xjRVPLpdAAk/Q==,type:str]
kind: Secret
metadata:
    name: secret-key-cred
sops:
    age:
        - recipient: age15n60jma8mrj5h7sqnal4lvlsn9usd0ceju0ked4t0mgewt8n6c7qtezm3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZTlRNFprMlpmZnJ6NzJT
            MUd2WnVnY3hMOU1wekZ3V1VYU2VXV0FCbFZnCld0RUpFSFZIUjNQSVZNdDNKWnhm
            TTZ1S1JNMXJpSUZ2RUhtb3RiaE5ibmMKLS0tIGJob3JLUE94OXpnU1NHU0ZHQkdN
            QUFHaW10UHFza1RsYm5DOC9rZTh6VjgK5NQUnRoK9GnxYMe3EQLr3w2mIsbB09Zs
            oqe10U29gUoXd589NfkdeRuH8qM2VwG0hpg9tLUiFw52aJRL5EmLXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T19:50:01Z"
    mac: ENC[AES256_GCM,data:q18UBPmw5MhHmDPo+yl4aPLU3RVK1Kp2PrLH0v5V+SjwDhPRzVzvm+SuIwiacuCAtu10rizOpGDwQ4bG6S3VHXdUskb33n3eCsCm8DWWT+vdhXoKqdYexamP897+8Co4hn3U6yEGQozI2ZIWSp/dQp92AgA6Pv4tuiR4nJxv4bo=,iv:pLuk6RSM8WQCX6exLghtB+ZVqsNRKppPbTxZVxsRp9Y=,tag:BGTw445DUfLgiTm2M9SMdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
