apiVersion: v1
kind: Secret
metadata:
    name: database-cred
    namespace: authentik
data:
    password: ENC[AES256_GCM,data:Viq4ncz6d1ktUO3OYiio+JwoJ+E4/FWcVhM/4gDLXQKzJ0tMWuTSFw==,iv:TFP73Y+k1/4Jonr1+9uHvIMHbI3SoWXUFsFuBxMQHp4=,tag:IvgkCQAzOW0U79qeSlNBMw==,type:str]
    postgres-password: ENC[AES256_GCM,data:FMLZcbogZrpFHEvg2JiYlRBQmLYK/lxFpexZ+Q8A+l15gtxXYLi7TQ==,iv:04/jAA3W/orkxyThC3+8y5guIgWWW8KABtayq5BD9A0=,tag:szw1hsm6L49fzYfNZeauaw==,type:str]
sops:
    age:
        - recipient: age15n60jma8mrj5h7sqnal4lvlsn9usd0ceju0ked4t0mgewt8n6c7qtezm3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQTR2UDdCTWo5blpEV2RN
            TlFtZEI1eXlad1ZKRmtEaDhxR2k5Mkk5L2ljCk9jL0ZSNm5uRkJxYW5RckNLd1pS
            c2R5Z3NuM3d1TWgyVGRxQnB6TzE0eW8KLS0tIFpWWmpLQ25lUk95d0hkZ1ZaUkNG
            a1VraFFGemNod3FLWXljL1RSY3hhd0kKAD02zeMm+GLShXw9NSGm40oVOZVS0vYu
            bnsPwcOGinOO0j7NLdd72Fl9ssGprU+4mvUTVYVhzRDWWAQL9FUU9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T18:41:05Z"
    mac: ENC[AES256_GCM,data:Y+jmpZEwakB6zrhgf7Tr1P/Yi4WdDTC9XpqLHmHlrvIKfCXJ2FXhSxq3D/4NsnjoE4vZ/cU6pEj2NiBXf+CVf0rDCtckzLn6w9oEwEvhu9wk89WMM5oEFu0U8ktqZChpfBxUB8MvXDFKJRfuor9parVwMGRq+LYCXyvdkiWKDHM=,iv:qqxnPvoCDP9f/z3bvKKzvmgfvYIdfoBo87Vig5JUq2w=,tag:jDhfR1ssS7vrkUOp2E+Cfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
