apiVersion: v1
kind: Secret
metadata:
    name: database-cred
    namespace: authentik
stringData:
    password: ENC[AES256_GCM,data:ug6IFn5iJ5g2bwnypM16l94Fzo4wYl6gk6vOOYZbiII2tAy+kiew5pPJLlCnpNjKG46PtXBWiHIbvBR6KKv6tuVBiHroTM9QAZcv4P7WeTc=,iv:0QYDa65jKWMILQ1+OGmsoSykpuOTM07Wt/1vE09RT1s=,tag:JZOFTYyWFEZbKlOuJtI6Fg==,type:str]
    postgres-password: ENC[AES256_GCM,data:AY9qpkv35TkBTUh+ZuyIPbbTQTL/57RV/fwaGPHpvUOaLy8oONaW1D96loEG17FRLHhu98aAxFQ1Q0D3QJjzU1VVU5DTW0eb4e8fp7j91rk=,iv:wcSq9yNR1k3CiibEagiReTZd1SGqSgPxWbh/Ngpg2ls=,tag:eoIN7WU5JGVCMFDEpDe4tw==,type:str]
sops:
    age:
        - recipient: age15n60jma8mrj5h7sqnal4lvlsn9usd0ceju0ked4t0mgewt8n6c7qtezm3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aHBQN2p6Z29jT3pFVnFq
            OGhYWXIxd3luYVlrSGNTcHlOQW5WYVRhRlRZCmwyUEh0ZUlSQVB5TUZjRURKeUJh
            WngvaGlCVVlIMjlRaWdVUTZrUXdWb0EKLS0tIEI3MFNKKzVHOURPNU1lTHFNM1Fh
            NWtSdWc4ZTFOOUp1dkoxckxJMzlWYXcKwakK2SPGSRUA9qPfTuD2YSaTIF+zl4KH
            4RHqSzQwm1gYTptNBAUeg+94O7LPPFi/2xPJeYeyrw0IlMXeV3XQ3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T18:49:56Z"
    mac: ENC[AES256_GCM,data:QBUdGMgPGGuGqL9rH4VjCVBzTRBrGRs4FeSq85cHBEq75+IJhrhdhBxuzsqnMLkl/OTCda5hc9sKpOjRY6JEPQLPFXR9mvjkEY9w2n0Hl2jJZp+CKwu5dOfpWhz0cqjRko8ye02e+iEYwQI/mNLA5KCz8xu/ndSxYeABFtq+ir0=,iv:L4vFBnvYEzc3j1/fbnagMNyk7ZcUoIEP7uGndkiJZWw=,tag:PIrAq6HRUmHCXTGRenMdnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
