apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./00-namespace.yaml
  - ./01-smtp.secret.yaml
  - ./02-certificate.yaml
  - ./03-secret-key.sops.yaml
  - ./04-database-cred.sops.yaml
  - ./05-helm-repository.yaml
  - ./06-helm-release.yaml