apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-pg
  namespace: paperless
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.9
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
  storage:
    size: 10Gi
    storageClass: longhorn-critical
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
