apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:Pm6I6SoVcKd+GTug4KleIiCamjegxIvcuOlgWIDsd6U+jcoOj4ZRKA==,iv:E9Ter3nC30+w9CXtTmy4qxCSmrk5xr3POn7KvZ6bq0Q=,tag:tcPQyyS4aoLdSpQFVPdY9g==,type:str]
sops:
    age:
        - recipient: age15n60jma8mrj5h7sqnal4lvlsn9usd0ceju0ked4t0mgewt8n6c7qtezm3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWXpMTVNjU3FPNzloQy9X
            RnBEaWJoTmdMcVM0bU5ma0hLQi9aNlRKd3lFCnFBRmM5TVVkdGVEemorc3QwcXUr
            L1JIZi9qZlBzWVJzRDErVHVRbDFpSXcKLS0tIExLdVdJUDVVT3I4SHMzU21FWDBz
            bXozelZTZWVCSFlGY3N0cXFyQjEwKzQKrtIMBsdx1oo/l/FNu3yiNzLVlvXMpqfa
            6iS3UrjVcN7GNVHDO4FatnK21Jr5m0gcyiiGCxCfDmZ+SeAjN+tpyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T21:28:01Z"
    mac: ENC[AES256_GCM,data:qIQ8eiyCXh0SDsQ2efQ5ROlEeyPdqKA6KnwTeqn+k6jcroASbpWR1FCEc1xMMB3wHrSzMmKRClWcT7HxsEB0Wz6DXuvRBStsk6z1sOHqkj+/f9tLrqLGisyWpPeg4CgQ9kTvssnju7ww5haYWpLTjCEQc5551/IgQHLw3V1Y++k=,iv:Ba+hiqltyr9hQLdS+8uWxoLNI8WBM/pc4CQ4asO3N1Y=,tag:knmHqVkq2VJpOOYSC0ZKEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
