---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-secret
  namespace: karakeep
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: karakeep-secret
  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: "c2ba5992-1f87-4752-b6f4-b4de00f56a36"
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: "a8e8b210-1866-4331-8b81-b4de00f587ae"

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openai-cred
  namespace: karakeep
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: openai-cred
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: "acb4f533-2404-4ed5-afd4-b4de00f52933"

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sso-client
  namespace: karakeep
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: sso-client
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: "bb3c0dd2-a3ac-4cf4-8de5-b4de00f61c2f"
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: "3c3895ed-8b6d-4227-a5f9-b4de00f63f0f"
