apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secret
    namespace: arr-stack
type: Opaque
stringData:
    OPENVPN_USER: ENC[AES256_GCM,data:+/2Em0n0KLeauxtCpxOj+4aeARio067w,iv:xUfQSD20gHwgEFHoIhTamaJTuw91g/nd/zh1VxGSe1w=,tag:7Aik6IhbZMgSOFH53Dn0ug==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:RYv6weAf50UPaMTmTavm0g4tMqEC3kW4,iv:zFTDBpgdzF6bexkpOcKn1TIHUX4/yRPNV3B/NBrXNWs=,tag:jLsd4DoH4pvx0vfvZgemfw==,type:str]
sops:
    age:
        - recipient: age15n60jma8mrj5h7sqnal4lvlsn9usd0ceju0ked4t0mgewt8n6c7qtezm3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbSt1YjRNeVBxRzRIcC9y
            ZGQvalFBL01rSnJ0WlZoQ1RYTlUvaXRES1F3CjBLeUNzVnFCdTJoNzhQcVhyUitE
            Y1lvYVZPZllOQzhUaUFmQ0ZPK3NBM3cKLS0tIEY3WkdZZEJ2RGJnQUphdjdNeTR6
            U3JaNCtCNGdIWnA4Zm45QTRhSWNvUzQKyGKMKxLI1MiPfdIQFxiSf8IDfSzAFaPV
            7ErQhrEQutTR2noZyKqMsp30zKPaZ7nk7OidPO7kPQMRWeEyXeeOUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T19:33:48Z"
    mac: ENC[AES256_GCM,data:EAVPoI6vyJr7yP9THDGVma+dVknnuWsE/X5OY4nFX6zXTmaFWStKAkwVL3adcB7kI7OB+KFqMZIn2KbMjSzTLue9HQE9jRDZP+AO02VFYN7GpPB3uDYbc38R50DR37t1ICv5w7juKc5As0/3e3FoXih331WSagfKPvAahQdUfio=,iv:lICyVbCtiK3qLrbI7w5Tp3QyWkEw9msaTWVSllBgdUM=,tag:OC8JHm0nS/yU6WjHDHVVjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
