apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secret
    namespace: arr-stack
type: Opaque
stringData:
    OPENVPN_USER: ENC[AES256_GCM,data:+/2Em0n0KLeauxtCpxOj+4aeARio067w,iv:xUfQSD20gHwgEFHoIhTamaJTuw91g/nd/zh1VxGSe1w=,tag:7Aik6IhbZMgSOFH53Dn0ug==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:RYv6weAf50UPaMTmTavm0g4tMqEC3kW4,iv:zFTDBpgdzF6bexkpOcKn1TIHUX4/yRPNV3B/NBrXNWs=,tag:jLsd4DoH4pvx0vfvZgemfw==,type:str]
    WIREGUARD_SECRET: ENC[AES256_GCM,data:bsGhP9dIcLDqrntKi13fsP7q3gAzyJEL05XYsD6tyNMVlsIJ9Yv9OOZP8kc=,iv:nt6DuPBfE5cdZyySeSIUerka9XKURh+LWlIZWs6CLDs=,tag:sLsBilTIdFM1IZJEt8clag==,type:str]
sops:
    age:
        - recipient: age15n60jma8mrj5h7sqnal4lvlsn9usd0ceju0ked4t0mgewt8n6c7qtezm3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbSt1YjRNeVBxRzRIcC9y
            ZGQvalFBL01rSnJ0WlZoQ1RYTlUvaXRES1F3CjBLeUNzVnFCdTJoNzhQcVhyUitE
            Y1lvYVZPZllOQzhUaUFmQ0ZPK3NBM3cKLS0tIEY3WkdZZEJ2RGJnQUphdjdNeTR6
            U3JaNCtCNGdIWnA4Zm45QTRhSWNvUzQKyGKMKxLI1MiPfdIQFxiSf8IDfSzAFaPV
            7ErQhrEQutTR2noZyKqMsp30zKPaZ7nk7OidPO7kPQMRWeEyXeeOUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T18:27:22Z"
    mac: ENC[AES256_GCM,data:dOwY2RmbToaREiy2zFcl3G8dvQu9GHwEDgZpXYW1ssCrOlucxtdl1Onp0BtkYwXGKscP0S7ZiZRIY0okZW3epoxTqSieXwaaOAOJsGAcESTSBiIZXs0p5+1AL+uQx6hDB9OuMrVlE4MuipiYwqVQpZpvqMq4rQ3gef2bkMdq4rs=,iv:3SxCYpLauxYenDPlOYubpUtd3QclwaU7uABRMsoAXHg=,tag:dA7rulN02GDQb70HPMbTjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
