---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-configmap-wireguard
  namespace: arr-stack
data:
  TZ: "Europe/Rome"
  VPN_SERVICE_PROVIDER: "nordvpn"
  VPN_TYPE: "wireguard"
  SERVER_COUNTRIES: "Italy,Germany,France,Netherlands,Switzerland,Spain"
  FIREWALL_OUTBOUND_SUBNETS: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
  DNS_KEEP_NAMESERVER: "on"
  DOT: "off"
  UPDATER_PERIOD: 4h
