apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./00-namespace.yaml
- ./01-secrets.sops.yaml
- ./02-pv-pvc.yaml
- ./03-prowlarr.yaml
- ./04-flaresolverr.yaml
- ./05-sonarr.yaml
- ./06-radarr.yaml
- ./07-bazarr.yaml
- ./08-qbittorrent.yaml