---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: radarr-secrets
    namespace: arr-stack
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: radarr-secrets
  data:
    - secretKey: apikey
      remoteRef:
        key: "92c92764-3845-4d1c-a702-b46500f7b9ae"