apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:tO0QbOAw92/uXIsORsH++ATEKXpBxcu5Yw==,iv:iWMawnFY/ZU/QXV0aBd9r1ND4knUkoFHK48h0nO6Y2A=,tag:72xd+mD14m1Z5lznI6PqeA==,type:str]
sops:
    age:
        - recipient: age15n60jma8mrj5h7sqnal4lvlsn9usd0ceju0ked4t0mgewt8n6c7qtezm3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTFp5V0VtZUdQSDhacHYy
            RklGdmNTVUI5eHBRQkxVZ0lBeG9QZVFYNVJvCkZ5a2VJR1hlU0svSTlwNkJUUllY
            bEQ2QXAyNStSZWtNMG1SSjZIVU4yZ2cKLS0tIHVja0Y4Skh5RUxYVzh6UG5jQVV5
            QmY2ZE56UFk0eXJrRGdFSHZ6Wnpyb3MK73OsoRQenuzuKjddNhzQ2XdM0vBWcnJ6
            Zp/vFSyYh6x709w8juDVnFvOVBH1kYonpx95CatdKI5vNuqlnwVUFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T16:57:23Z"
    mac: ENC[AES256_GCM,data:a0K9iUhCQD+j2Dlqf4Pxiq6R2RWSvFCEDI8OE7wFY8NuV8u+PY+PoxGTMvMY3SWWQ38zcP7XrBXEr92Zq7Oc8fZH8cqpWgNqLhJ/dnlQ9ki/LPo48XzIWtqgWNNpY+I1wMxHG1rV1rMq3tK8z1E/Qd0sERTyGqbKI86ijWZXgmY=,iv:N+X3KoFq/G1zyz69RE88y3CQ3BAo4ecjSKYk+FLBlRc=,tag:SlNMyOxVgwT9RYbDWm/xwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
