---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: qbittorrent-secret
    namespace: qbittorrent
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: qbittorrent-secret
  data:
    - secretKey: GLUETUN_CONTROL_SERVER_API_KEY
      remoteRef:
        key: "e0faf96e-15b6-4ea4-80fa-b439014adab1"
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: "055bea50-dff6-4e37-ae21-b439014a8ce4"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-gluetun
  namespace: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: qbittorrent-gluetun-secret
    creationPolicy: Owner
    template:
      data:
        auth.toml: |
          [[roles]]
          name = "gluetun-qb-port-sync"
          routes = [
            "GET /v1/publicip/ip",
            "GET /v1/openvpn/portforwarded"
          ]
          auth = "apikey"
          apikey = "{{ .GLUETUN_API_KEY }}"
  dataFrom:
    - extract:
        key: e0faf96e-15b6-4ea4-80fa-b439014adab1