---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: planka-secret
    namespace: planka
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: planka-secret
  data:
    - secretKey: secret-key
      remoteRef:
        key: "e1b1d0d8-dbc5-44f7-a193-b48900b05017"
    - secretKey: admin-password
      remoteRef:
        key: "455d459d-6f66-4732-bc58-b48d00bfed4c"

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: sso-client
    namespace: planka
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: sso-client
  data:
    - secretKey: client_id
      remoteRef:
        key: "c6c5e57f-12a7-4f86-b67b-b48900afc235"
    - secretKey: client_secret
      remoteRef:
        key: "de0df7eb-61da-4ff0-bc90-b48900afe709"

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: smtp-cred
    namespace: planka
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: smtp-cred
  data:
    - secretKey: username
      remoteRef:
        key: "d8fcb942-7ea3-4c0a-8f12-b43f010f7f99"
    - secretKey: password
      remoteRef:
        key: "2e015fb6-acaa-4162-9861-b43f010f8fff"