apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: planka-data
  namespace: planka
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 10Gi