---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: autobrr-oidc-secrets
    namespace: arr-stack
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: autobrr-oidc-secrets
  data:
    - secretKey: client_id
      remoteRef:
        key: "8403c249-d344-4345-a271-b4b2011d026d"
    - secretKey: client_secret
      remoteRef:
        key: "cf56a775-24c6-4381-a3c4-b4b2011d1d6c"