apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-autobrr-config
spec:
  capacity:
    storage: 1Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-default
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: autobrr-config-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autobrr-config
  namespace: arr-stack
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-autobrr-config