---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: default-snapshot
  namespace: longhorn-system
spec:
  cron: "0 */6 * * *"
  task: snapshot
  groups: []
  retain: 5
  concurrency: 1
  labels:
    tier: default
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: default-backup
  namespace: longhorn-system
spec:
  cron: "0 2 * * 0"
  task: backup
  groups: []
  retain: 4
  concurrency: 1
  labels:
    tier: default