---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-oidc-secrets
  namespace: home-assistant
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: home-assistant-oidc-secrets
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: "aed78215-b8fc-4db6-8c9c-b4d700e89e75"
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: "0d118d2c-e35a-41f2-82e9-b4d700e8a977"
