---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: sso-client
    namespace: mealie
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: sso-client
  data:
    - secretKey: client_id
      remoteRef:
        key: "4d999320-6eac-4148-ae58-b478011788c2"
    - secretKey: client_secret
      remoteRef:
        key: "32aeef4a-3b12-4671-a0ab-b47801179c23"