---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bitwarden-secret-manager
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://gitlab.com/gp-homelab/k8s/bitwarden-secret-manager.git
  ref:
    branch: main
  secretRef:
    name: gitlab-deploy-token
