apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-bitwarden-secret-manager
  namespace: flux-system
spec:
  interval: 5m
  path: ./polaris
  prune: true
  sourceRef:
    kind: GitRepository
    name: bitwarden-secret-manager
  dependsOn:
    - name: infra-bitwarden-sdk-server
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: bitwarden