---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: database-cred
    namespace: authentik
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: database-cred
  data:
    - secretKey: password
      remoteRef:
        key: "895f53a8-05c9-428b-97b8-b41800afb0a2"
    - secretKey: postgres-password
      remoteRef:
        key: "f6b4de1b-8dbd-4e38-88f0-b41800afeb80"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: secret-key-cred
    namespace: authentik
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: secret-key-cred
  data:
    - secretKey: secret_key
      remoteRef:
        key: "047282e5-e21d-4480-9c59-b41800b035a2"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: smtp-cred
    namespace: authentik
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: smtp-cred
  data:
    - secretKey: username
      remoteRef:
        key: "b5001659-dc5e-41de-a195-b41800b095cd"
    - secretKey: password
      remoteRef:
        key: "d059117e-ed02-451b-83f5-b41800b0ac32"