apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: cloudflare-token
    namespace: cert-manager
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: cloudflare-token-secret
  data:
    - secretKey: cloudflare-token
      remoteRef:
        key: "c20139d3-2d39-4cf2-8af2-b41400ddcd3f"