apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: ${BITWARDEN_API_URL}
      identityURL: ${BITWARDEN_IDENTITY_URL}
      organizationID: ${BITWARDEN_ORG_ID}
      projectID: ${BITWARDEN_PROJECT}
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt
      auth:
        secretRef:
          credentials:
            name: bitwarden-token
            namespace: external-secrets
            key: token