apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-token
  namespace: external-secrets
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
type: Opaque
stringData:
  token: ${BITWARDEN_TOKEN}
