apiVersion: v1
kind: Secret
metadata:
    name: bitwarden
    namespace: flux-system
type: Opaque
stringData:
    BITWARDEN_URL: ENC[AES256_GCM,data:dXxndxEf/kmKZsX4O8eEBsLhdqD8G7nh7twipCVbUg==,iv:EJW0gNJgOip2tJGwYJmmO9K886jz0yhugHIvRM5k2ww=,tag:668d3jmoca7mT8SU9xECzg==,type:str]
    BITWARDEN_ORG_ID: ENC[AES256_GCM,data:GMihtbraQ1ZWTbmQEPb6XzCXcnuw1irSO//baaO6AkBq9+Pa,iv:Rw/nwtBy4hR/xbNSMPHC5VO1epuZYFEoJGyu8z59vJU=,tag:Qf15H1QIiPW2uYNd+D+lQA==,type:str]
    BITWARDEN_PROJECT: ENC[AES256_GCM,data:rPAlk2qeBinwRBrwSQxAYiJg+KScyKV2iCyLxROXmu7ho8fj,iv:XT1myM/JNwYNkmliuwvIkzhQg2MLbUyJ/aIIiRdtXC8=,tag:ILl9rx1pqYR4KOdavgykHQ==,type:str]
    BITWARDEN_TOKEN: ENC[AES256_GCM,data:DjsxOUM5xUyYiQvyeHBA+9mk4ud/8+fegDdlIi/ZZigXT4u8noj7mrJ2QPh0+UZdoB7Md1LkN1wK2POTlT4/WxBqOmRs4vM6cK6n18FIk2Gh7v5K3m3E7sT9OrsUYA==,iv:3uuPGxC/SdIpVV8v4QFdCgNFInws7VK35ztd2tEKGQ4=,tag:KQOPX6DxJCgs6RAFM/KIsg==,type:str]
sops:
    age:
        - recipient: age15n60jma8mrj5h7sqnal4lvlsn9usd0ceju0ked4t0mgewt8n6c7qtezm3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMVFFWXNCQjVMVHBSU3hW
            Q3hnN3RLeFFFeGdTQk54TXBVN2l6aTVxZlFvCkxKZGc1bWxZblFSeFJuZzZiamVz
            MW56T2ZDMkphcFJGb3dINVBYaVVxZUkKLS0tIHR6WUlRVGhoVnBQY1FZZDdaeDRx
            QWVGWXVWUEorVHNQeXZrY0xWM1JVd1UKeeTWyrXJTrQRYrbnpdj6YjsddnKnJCZG
            OMSoeX7QDNZQplll/YZ3HzZo5gsyKUgG4VGKz8Y/mCyzdMaMjqbMdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T17:58:55Z"
    mac: ENC[AES256_GCM,data:PslFG4HZlh6x4V9b43T9Q9rBzjlbgalcYbl7k358gqAwC8Y7DferQ6ClRv+pZlThC75ijEaRYDfyA6sSHzBib5+S599PHqRIIOQehlBm8Q+Wcfz1l6W/0Idkvr364+NkmTRbqcmcU0hd3StpqVtHSD2VUwaUlVnUJQD/S97W0Ko=,iv:S2WuIZCKj2ipdWUorO2TGY7blKHwRkM7U95O1Hv0HDk=,tag:RPa54zWLbLexckNdWHnxjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
