apiVersion: v1
kind: Secret
metadata:
    name: gitlab-deploy-token
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:IXpZ5849nEAO0+EIDho=,iv:HQ0LWwXFYBI3o+OgUzd3wyOvf5So7tZIGjQA24/kqCg=,tag:5AkspCDu5DTk92xmylZefg==,type:str]
    password: ENC[AES256_GCM,data:tzRrTMazzltUE1Rj6weV1CbXzAK0X4aL1g==,iv:j/k5t4tQLwTfW3lpWqyKczvEKFZ7JGub0VfNKYrsFnw=,tag:txH7JP3S7LYlmHxZv+c1jQ==,type:str]
sops:
    age:
        - recipient: age15n60jma8mrj5h7sqnal4lvlsn9usd0ceju0ked4t0mgewt8n6c7qtezm3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZG5WemVieU1DM1JRanJo
            QzRiWGFkU2pEOTZXQjNOc2pIZlU2QThRblNBCkduaE5LdzNZaCtnVDRUTm1xa2Rk
            L2syV0w2TEJaVHFsSi9ZaDFJNDZwdGMKLS0tIFprNjRCeWkycEdRWnBrYnZ4eSs2
            d3FpWUJDQlA0NSsrS1NjOGJncmZtMW8Kpc3oVS+OFOFni5EHwdKTNA2E7PdtIONt
            cblQGvD+9NyBipLN/IaMlJswuePu2guahuJwFRtG0r25lFvKmmVmEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T16:20:25Z"
    mac: ENC[AES256_GCM,data:mCKo+1g9iAsgn+0MZyWUCrkCFuCNd4T4tBzC4Pe11pdi1vDjtExKzudUtNqD1w5N+lkC1iPVnTWf24+oQZN2Om/4Kx3sGnQKz3oD6K2UrDkckSO6YFTnIaQxOeFpFrWSR3SjSXWtHbX2/ptcACL4Wdz5/Tl7hv5xiq0CGHtJFVw=,iv:4ISjW0L/9QIeZrEESBINKCPyGKDm6LLGLCySWTJ25ls=,tag:0bhjSrOwKHRY3hg1SKyMxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
