apiVersion: v1
kind: Secret
metadata:
    name: bitwarden
    namespace: flux-system
type: Opaque
stringData:
    bitwarden-url: ENC[AES256_GCM,data:Vus9F1xBK45NIanUf05rwkFSIH+EufKnvysxpcd1ag==,iv:9yy8LaicX3q/++c8ymqNPlL+gWZpeUE1LrxetjSgNCk=,tag:p22V+OgM1yQcNucOqmBapA==,type:str]
    bitwarden-id: ENC[AES256_GCM,data:MwbVY3yFCWvd0wZtpVB8Nl1Il749v0GiBvQbD6sPMELI2mHD,iv:Qd2RWs/48eIlpg3hJWwJeCbCT2XQQee8wrpK7gfDqg0=,tag:lMhnvPgKmbOMA7E3gHu8Sw==,type:str]
    bitwarden-token: ENC[AES256_GCM,data:H0fCGtqw15Fup408vEicvWmZ5o1yYh2AaqnTQwWNdppy4YmbWV3NKsgTAfWxdV3jhQ7CAambL3ypfF/9jtdZR4ju+CwF6U7arAYX0uI4Oie7+HYl+C3s8Pe6xHUtow==,iv:w8wriaohBJM2CMZXlqNaIYq9WU0qc+IoGIdkxE5D83Q=,tag:tkmZpXbiq9lvYrxaL9QhRA==,type:str]
sops:
    age:
        - recipient: age15n60jma8mrj5h7sqnal4lvlsn9usd0ceju0ked4t0mgewt8n6c7qtezm3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUlVOV1Q5Mk95UHFDZmwz
            Y2FtNEVnb084Uks4TURoMUxWVlV6RUxRVkJrCkovN2dEZTUrQ2tNSXZsbEUxbFA4
            OUdDSVdPT2d6c08zcldza1JsRVllV0EKLS0tIDdBM05GREpRVFFORmdRRDZGUFZ0
            UjJkcGpBSzA4cklNRzQ2WVlpS3ExVEEKFQPEZRx7zLJUB2fWoPZP/9MiAVLkDcua
            wPMjcllAQyHi9J34vyMLiRtEVy6AjoVfJmz2vLISIFPYGcBWe4Dg/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T16:20:30Z"
    mac: ENC[AES256_GCM,data:dTBxH0AkdFtR4D7tHXG/CNosm+lFmb2zt/P8ppIwJOFQqSMBXc+CVXwFqM7k+PahHvWIcGsv2Ys4M7k//H1nWQsSqBbefKy9s03f847NcP8Vogk0u3pP7hjvolU3F794l2xet1ELNFYHi287BjZ1BrQUfuoHMUhOG3wyzIh6M2I=,iv:p9H2c7ulWr+r5MIn3FY6BHec0Z8uY/7zqycvAsy62kM=,tag:EN2DlTxrRESe6/w4FrphIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
