apiVersion: v1
kind: Secret
metadata:
    name: bitwarden
    namespace: flux-system
type: Opaque
stringData:
    BITWARDEN_API_URL: ENC[AES256_GCM,data:011xfO7nOSP9MpbhKUQcA3cKmygpdBWFCPRQFA9OGA==,iv:4yA2JLfGcJqOUmcr5S/SBW5VhnuNbo76YICJw28K7+8=,tag:4F4Tnz7e21OI5Mpn0k9LRA==,type:str]
    BITWARDEN_IDENTITY_URL: ENC[AES256_GCM,data:7qLdUrjQijPr3SZUxPj165oAhGt/sriUUfQmx/NGuz965vvT,iv:fyrIY1YxIxkI++ykwbNVrYFunxHZdfHhRxaICiTM9tc=,tag:lOODODroH31FGeEjkKkNNg==,type:str]
    BITWARDEN_ORG_ID: ENC[AES256_GCM,data:GMihtbraQ1ZWTbmQEPb6XzCXcnuw1irSO//baaO6AkBq9+Pa,iv:Rw/nwtBy4hR/xbNSMPHC5VO1epuZYFEoJGyu8z59vJU=,tag:Qf15H1QIiPW2uYNd+D+lQA==,type:str]
    BITWARDEN_PROJECT: ENC[AES256_GCM,data:rPAlk2qeBinwRBrwSQxAYiJg+KScyKV2iCyLxROXmu7ho8fj,iv:XT1myM/JNwYNkmliuwvIkzhQg2MLbUyJ/aIIiRdtXC8=,tag:ILl9rx1pqYR4KOdavgykHQ==,type:str]
    BITWARDEN_TOKEN: ENC[AES256_GCM,data:DjsxOUM5xUyYiQvyeHBA+9mk4ud/8+fegDdlIi/ZZigXT4u8noj7mrJ2QPh0+UZdoB7Md1LkN1wK2POTlT4/WxBqOmRs4vM6cK6n18FIk2Gh7v5K3m3E7sT9OrsUYA==,iv:3uuPGxC/SdIpVV8v4QFdCgNFInws7VK35ztd2tEKGQ4=,tag:KQOPX6DxJCgs6RAFM/KIsg==,type:str]
sops:
    age:
        - recipient: age15n60jma8mrj5h7sqnal4lvlsn9usd0ceju0ked4t0mgewt8n6c7qtezm3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMVFFWXNCQjVMVHBSU3hW
            Q3hnN3RLeFFFeGdTQk54TXBVN2l6aTVxZlFvCkxKZGc1bWxZblFSeFJuZzZiamVz
            MW56T2ZDMkphcFJGb3dINVBYaVVxZUkKLS0tIHR6WUlRVGhoVnBQY1FZZDdaeDRx
            QWVGWXVWUEorVHNQeXZrY0xWM1JVd1UKeeTWyrXJTrQRYrbnpdj6YjsddnKnJCZG
            OMSoeX7QDNZQplll/YZ3HzZo5gsyKUgG4VGKz8Y/mCyzdMaMjqbMdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T18:15:02Z"
    mac: ENC[AES256_GCM,data:S9J5qlm69FbgCyWj9i3/13oRPNmpdnfXm8A8eAuDV73VtcuqAOZO08432U1X3cfLCJ/W02uc8fioaS1iytAFVCvhB9yJzZxRbK5/4IZevAMdkzSdULF77a2DuVV/ow6jX8xwnfpmVusjRl+2Cqvm1SMQY1HhEb2ffieuCgENt3c=,iv:d4TFOwMBYX09vJaxenYNUsS6HAg3sDjMsEEwTQY7Q7o=,tag:6Tn4jb6ab7UEQRY+777vJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
