apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret
    namespace: flux-system
type: Opaque
stringData:
    gitlab-token: ENC[AES256_GCM,data:y1XVepyNyXgt9lqQoHG3LigPmQaaKe9iOQ==,iv:a6fjhSJFDUFSau8pvQerzpRH7XavacaDnYBZd1UV6vE=,tag:9/UexQsj9hzoMtzym7gH9w==,type:str]
    bitwarden-url: ENC[AES256_GCM,data:HUWmPFhjCxXTryFCug960zSGu0XNlvrA9tZK0l8kOA==,iv:0yi/NC1usM2IXm4Sm1lC01nUKMK5TnssBztbfuiZekU=,tag:ObIkrDV5HdQ3hnjP5YkA7Q==,type:str]
    bitwarden-id: ENC[AES256_GCM,data:WFaFcWP8HvdY/FJdtraAtQmFRv+5Idk+gyYnWYH9u36LvqRC,iv:Nu/dhyu69l7Gn4KAvHJPosrRCpCZnt+jH5goLLWqNEs=,tag:T1trNaoAAvki+k5KP0DHRw==,type:str]
    bitwarden-token: ENC[AES256_GCM,data:zYkEG2liz4whY6BaxZpm909qAusf/8+NRml4kviGkoCnSHJf54mGEC9JzjMQTX3ZuLoJIpXWnFEI7+lupLEGH5e80w2Sc+6hv5Bqekh3Xy12u0qT2yfGoBOGZVzOoQ==,iv:6N8EOdToTrxjM/937XoKjD2tk/cPAgzfNiRNlX5b+8E=,tag:f0QGM/lrWDOAeislhrVgMA==,type:str]
sops:
    age:
        - recipient: age15n60jma8mrj5h7sqnal4lvlsn9usd0ceju0ked4t0mgewt8n6c7qtezm3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNc2lNWGkycWxNVHBLLytl
            aktEVGNGR3lNdEhJcGF6Wjg5cXpyRHBJb0VjCjhYUDZhOFhjeE91ckVHWmhWQzkw
            MTZoMmw4di9BdFk2YVRjbnBMU0pKbGMKLS0tIGpCbzJxZmRhaERING82R3dUbG9T
            NjlJcDRnT3ZwUnAwRGs5NmpiMmNaek0KKdYB0WboxAELJVskzgYfiLSPl0lH1O4q
            /auN3aeqprE4PhSQK3NABquGbQ+4/UL0hIymBukKcEOEgm7rKioWHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T15:49:06Z"
    mac: ENC[AES256_GCM,data:e7/5NMNaMigh2lkVUD1x5HB8QI3II1Ygi8X3ybWG8OOocHuPoWraZu2z9Uy0VUPa7uQ7rIyVxfa/5vrLFgmwjVeW4m3Na5ru6iIjwkSkxKqqhB4LmNd/QuwM8QY1aJcMjE6aO4AzZy6Yv1ACoQnfVmsr98T2zDN7bM/EPpmm328=,iv:dRj39UqoUzGlEGSiLcXYSvlinXaYJHVV0UBT9SigQWQ=,tag:kySxqVRzuHmdtXQmkZeQTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
