apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-seerr-config
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-default
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: seerr-config-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config
  namespace: seerr
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-seerr-config