---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-jellyfin
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nolock
    - soft
    - rw
  nfs:
    server: ${NAS_DOMAIN}
    path: /volume1/media/media

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-jellyfin-pvc
  namespace: jellyfin
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  volumeName: media-jellyfin