apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: grafana-oauth-secret
    namespace: grafana
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: grafana-oauth-secret
  data:
    - secretKey: client_id
      remoteRef:
        key: "4940091f-5a4f-49a4-8530-b45a00dfe4c5"
    - secretKey: client_secret
      remoteRef:
        key: "968fc0da-a919-4067-b70b-b45a00dff808"