apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-config
  namespace: forgejo
spec:
  storageClassName: longhorn-critical
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-data
  namespace: forgejo
spec:
  storageClassName: longhorn-critical
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi