---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: volume-backups
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://gitlab.com/gp-homelab/k8s/volume-backups.git
  ref:
    branch: main
  secretRef:
    name: gitlab-deploy-token
