apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: paperless
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: broker
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-role/worker
                    operator: In
                    values: ["true"]
      containers:
        - name: broker
          image: docker.io/valkey/valkey:9.1.2-alpine
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: broker-data
              mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: broker-data
          persistentVolumeClaim:
            claimName: broker-data
