apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-data
  namespace: paperless
spec:
  storageClassName: longhorn-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
