---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: secret-key-cred
    namespace: authentik
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: secret-key-cred
  data:
    - secretKey: secret_key
      remoteRef:
        key: "c79657ac-d9c5-4b3e-b600-b43f010fc402"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: smtp-cred
    namespace: authentik
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: smtp-cred
  data:
    - secretKey: username
      remoteRef:
        key: "d8fcb942-7ea3-4c0a-8f12-b43f010f7f99"
    - secretKey: password
      remoteRef:
        key: "2e015fb6-acaa-4162-9861-b43f010f8fff"