apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-vars.yaml
  # Controller
  - cert-manager/ks.yaml
  - metallb/ks.yaml
  - traefik/ks.yaml
  - longhorn/ks.yaml
  - intel-nfd/ks.yaml
  - intel-gpu/ks.yaml
  # Configs (dipendono dai rispettivi controller)
  - cert-manager-config/ks.yaml
  - metallb-config/ks.yaml
  - traefik-config/ks.yaml
  - longhorn-config/ks.yaml

patches:
  - target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
    patch: |
      - op: add
        path: /spec/postBuild
        value:
          substituteFrom:
            - kind: ConfigMap
              name: cluster-vars
  - target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
    patch: |
      - op: add
        path: /spec/decryption
        value:
          provider: sops
          secretRef:
            name: sops-age