apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "41.0.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 1h
  
  install:
    crds: Create

  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
  
  values:
    service:
      type: LoadBalancer

    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.${CLUSTER_DOMAIN}`)
        entryPoints:
          - websecure
        tls:
          secretName: dashboard-traefik-tls

    providers:
      kubernetesIngress:
        publishedService:
          enabled: true

    api:
      dashboard: true
      insecure: false

    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      # websecure:
      #   http:
      #     middlewares:
      #       - traefik-traefik-real-ip@kubernetescrd

    extraObjects:
      - apiVersion: traefik.io/v1alpha1
        kind: Middleware
        metadata:
          name: traefik-real-ip
          namespace: traefik
        spec:
          plugin:
            traefik-real-ip:
              excludednets:
                - 10.10.0.0/16
                - 10.244.0.0/16
                - 10.96.0.0/12
                - 192.168.0.0/16
                - 172.16.0.0/12
      - apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: dashboard-traefik-certificate
          namespace: traefik
        spec:
          secretName: dashboard-traefik-tls
          issuerRef:
            name: letsencrypt
            kind: ClusterIssuer
          commonName: traefik.${CLUSTER_DOMAIN}
          dnsNames:
            - traefik.${CLUSTER_DOMAIN}

    experimental:
      plugins:
        traefik-real-ip:
          moduleName: github.com/soulbalz/traefik-real-ip
          version: v1.0.3
