---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: qbittorrent-secrets
    namespace: arr-stack
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: qbittorrent-secrets
  data:
    - secretKey: pia-main-user
      remoteRef:
        key: "5567ee9c-31e8-47ec-9344-b4650111a963"
    - secretKey: pia-main-password
      remoteRef:
        key: "938bedf5-a105-4405-8d46-b4650111b77f"