apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik/ks.yaml
  - ./arr-stack/ks.yaml
  - ./seerr/ks.yaml
  - ./plex/ks.yaml

patches:
  - target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
    patch: |
      - op: add
        path: /spec/postBuild
        value:
          substituteFrom:
            - kind: ConfigMap
              name: cluster-vars
  - target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
    patch: |
      - op: add
        path: /spec/decryption
        value:
          provider: sops
          secretRef:
            name: sops-age