apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:jB1uaJksYKQg3dNyZ7Er1kmGKas6w/0pb/Y69UNuR9Z+AwBcSiKvR/PzaTzmXoxcZnqUbLI=,iv:6hkTk1SWCaHFQwGE6yaU+stIrZb9HVmPjVIMrezV8ko=,tag:Fd0E3vSAOCCG9NpB9c33bQ==,type:str]
sops:
    age:
        - recipient: age15n60jma8mrj5h7sqnal4lvlsn9usd0ceju0ked4t0mgewt8n6c7qtezm3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNVNOMUgxMDdqUDBmN0d0
            WDVDTk11Q2pXL3R0TldPQ3BOallpT3ltVHk4CkQ1OXV5SHlETHE4Rm42Tm1CSEhF
            YkRDaVhlb3l6Z0VpZ3didmdldkhoQmMKLS0tIDdLUExKSnpadnFzZXJhTW5OaSsx
            MkNsQjdFaE9hV2pmcWZtdnV6dmFibzQKxWlIT4BLO7+fp6aC/zYLcbMtz8XXmt3/
            Vm1HW6c2R+Bx5x7E6undsEr/OJ7vrs+HHT1zmjCgU6zCT2oUAGQ7gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T16:53:07Z"
    mac: ENC[AES256_GCM,data:bV/YQUeExotzLSCC6HL8NYXNxAyrEPtBo9Fp8BuigStNWdOAGzvdaPGybv5qT14VYEbujF5cnvW8UES4Q+wNU6eAmrmBEpK/xI31Uhi7SaGB7ivIbBwQA5GLdV2csZsq9toFHabqSvvamIWyKSfSJXzR2IgcgqTBLw9HcdMdNSk=,iv:ZtPCgRN8F67dyB9RDQpjOneLo7kw6ZZJa2zVyjZPA+M=,tag:MBWXIp2Gct0kEA3cLHX4pQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
