---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-ephemeral
  annotations:
    longhorn.io/description: "Volumi temporanei, nessun backup"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fsType: ext4
  dataLocality: strict-local