---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret
  namespace: paperless
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: paperless-secret
  data:
    - secretKey: secret-key
      remoteRef:
        key: "5b1d9f96-28b1-4eb5-90f9-b4c900ded70a"
    - secretKey: admin-password
      remoteRef:
        key: "9af9a4e3-bd7d-498c-a20e-b4c900e6c939"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sso-client
  namespace: paperless
spec:
  refreshInterval: 1h0m
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: sso-client
    template:
      engineVersion: v2
      data:
        client_id: "{{ .client_id }}"
        client_secret: "{{ .client_secret }}"
        oidc-providers: |-
          {"openid_connect":{"APPS":[{"provider_id":"authentik","name":"Authentik","client_id":"{{ .client_id }}","secret":"{{ .client_secret }}","settings":{"server_url":"https://sso.${CLUSTER_DOMAIN}/application/o/paperless/","scope":["openid","profile","email","groups"]}}]}}
  data:
    - secretKey: client_id
      remoteRef:
        key: "181312d3-6a84-4b8b-9c59-b4c900e63b9f"
    - secretKey: client_secret
      remoteRef:
        key: "dd24192a-5aa4-455f-8d72-b4c900e652a0"
